dependencies:
  - name: web-ui
    version: 0.1.0
    repository: file://../web-ui
  - name: api-gateway
    version: 0.1.0
    repository: file://../api-gateway
  - name: download-service
    version: 0.1.0
    repository: file://../download-service
  - name: upload-service
    version: 0.1.0
    repository: file://../upload-service
  - name: file-service
    version: 0.1.0
    repository: file://../file-service
  - name: authenticator
    version: 0.1.0
    repository: file://../authenticator
  - name: user-service
    version: 0.1.0
    repository: file://../user-service
