# Default values for cra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: bluehub.azurecr.io
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  rpcPort: 6000
  name3: none
global:
  ingress:
      hosts:
        - ''
ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/add-base-url: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /    
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*.northeurope.cloudapp.azure.com"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "5242880m"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1d"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1d"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1d"
  # hosts:
  #   - 'kd-stream.northeurope.cloudapp.azure.com'
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
deployment:
  health:
    enabled: false
    checks:
      livenessProbe:
        httpGet:
          path: /health
          port: 3000
          httpHeaders:
          - name: authorization
            value: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJAZG8ifQ.k1sGqvw0IJ1ocB9XrF8Oviaz4D-A4E9fDkz_VmAY-LA
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 3000
          httpHeaders:
          - name: authorization
            value: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXJAZG8ifQ.k1sGqvw0IJ1ocB9XrF8Oviaz4D-A4E9fDkz_VmAY-LA
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
